# Generated by Django 4.2.8 on 2024-02-03 09:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0002_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
