# Generated by Django 4.2.8 on 2024-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0004_post_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('LANDLORD', 'Landlord')], max_length=50),
        ),
    ]
