# Generated by Django 4.2.8 on 2024-02-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0006_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
