# Generated by Django 4.2.8 on 2024-02-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0007_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
