# Generated by Django 4.2.8 on 2024-02-25 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0008_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter correct format phone number, ex: 0987654321', regex='(0[0-9]{9,10})$')]),
        ),
    ]
