# Generated by Django 4.2.8 on 2024-02-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0009_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='acreage',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
