# Generated by Django 4.2.8 on 2024-02-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseapp', '0010_post_acreage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='acreage',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
